### ISSUE TITLE
CLI improvements 3/n

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#114]

**Comment by NealArw** [comment]
:point_right: **1.** @gadkins Hello! How did you get an error `Not found` after `uffizzi login` command? Please, could you describe with more details.

**2. TESTED - OK**

```
bash-5.1# bundle exec uffizzi login
Login to Uffizzi server.
Login successfull
bash-5.1#
```

:point_right: **3.** Needs to remove substring `UffizziCore::` from the output.

```
bash-5.1# bundle exec uffizzi project compose describe
UffizziCore::ComposeFile Not Found
bash-5.1# bundle exec uffizzi project set-default test
UffizziCore::Project Not Found
bash-5.1# bundle exec uffizzi preview list
The project has no active deployments
bash-5.1# bundle exec uffizzi preview describe deployment-1
UffizziCore::Deployment Not Found
```

:point_right: **4.**  Needs to add single quotes around the service name in the error whew image does not defined in the compose file:

```
bash-5.1# bundle exec uffizzi preview create test-compose/uffizzi-compose-webhook-docker.yml
Service webhooks-test-app has neither an image nor a build context specified. At least one must be provided.
```
E.g. file:

```
services:
  webhooks-test-app:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true  
```
