### ISSUE TITLE
New subcommands for connecting a docker registry are needed

### ISSUE THREAD

**Issue by antlu** [UffizziCloud/uffizzi_cli#124]
Description https://github.com/UffizziCloud/uffizzi_app/issues/34#issuecomment-1183564956

**Comment by antlu** [comment]
Input data can be read from these environment variables:
- DOCKER_REGISTRY_URL 
- DOCKER_REGISTRY_USERNAME
- DOCKER_REGISTRY_PASSWORD

**Comment by antlu** [comment]
The environment variables are mentioned in https://github.com/UffizziCloud/uffizzi_cli/issues/124#issuecomment-1188796088
The commands are:

1. `uffizzi connect docker-registry`
2. `uffizzi disconnect docker-registry`

Options for `connect`:
```
OPTIONS
       -r, --registry=<registry>
              URL of the service.

       -u, --username=<username>
              Username for the service.

       -p, --password=<password>
              Password for the service.
```
As a registry I used [JFrog Artifactory](https://jfrog.com/artifactory/).
With this compose file:
```
services:
  web:
    image: antlu.jfrog.io/default-docker/antlu/hello
    command: ["python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000

x-uffizzi:
  ingress:
    service: web
    port: 8000
```

**Comment by NealArw** [comment]
**TESTED - OK**

```
services:
  webhooks_test_app:
    image: elnealo.jfrog.io/uffizzi-test-docker/webhook-test-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-jfrog.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] webhook-test-app
{"id":"deployment-2","url":"https://deployment-2-testet-pw9l4a.app.qa-gke.uffizzi.com"}
```

**Comment by NealArw** [comment]
```
bash-5.1# bundle exec uffizzi connect docker-registry
Registry Domain: elnealo.jfrog.io
Username: danila.polovinkin@dualbootpartners.com
Password:
Successfully connected to Docker Registry.
```

**Comment by NealArw** [comment]
```
bash-5.1# bundle exec uffizzi connect docker-registry -r elnealo.jfrog.io -u danila.polovinkin@dualbootpartners.com --update-credential-if-exists
Updating existing credential.
Password:
Successfully connected to Docker Registry.
bash-5.1#
```

**Comment by NealArw** [comment]
```
      DOCKER_REGISTRY_URL: elnealo.jfrog.io
      DOCKER_REGISTRY_USERNAME: danila.polovinkin@dualbootpartners.com
      DOCKER_REGISTRY_PASSWORD: 
```

```
bash-5.1# bundle exec uffizzi connect docker-registry --update-credential-if-exists
Updating existing credential.
Successfully connected to Docker Registry.
bash-5.1# bundle exec uffizzi disconnect docker-registry
Successfully disconnected from Docker Registry.
bash-5.1#
```

**Comment by moklidia** [comment]
@NealArw We need to test it with CloudSmith too 
https://help.cloudsmith.io/docs/docker-registry

**Comment by NealArw** [comment]
**TESTED - OK** cloudsmith.io

```
services:
  webhooks_test_app:
    image: docker.cloudsmith.io/dbp-test/webhook-test-app/webhook-test-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
