### ISSUE TITLE
Change uffizzi connect to update existing credentials

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#130]
From Adam:

What's the behavior of uffizzi connect if you specify environment variables but there are already credentials on the account? How does that behavior change with the --skip-raise-existence-error flag? I see this option demonstrated within the entrypoint script (good) but I do not see it documented anywhere.

Is there a way to change existing credentials without doing uffizzi disconnect? For execution in CD pipelines, we need a way to do this. With a flag is fine; I think overwriting as the default behavior is probably fine too?

**Comment by moklidia** [comment]
Let's add `--update-credential-if-exists` flag. If this flag is passed, we need to update the credential if it exists in the database.

**Comment by antlu** [comment]
Usage example
```
DOCKERHUB_USERNAME=name DOCKERHUB_PASSWORD=password uffizzi connect docker-hub --update-credentials-if-exist
```

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi connect docker-hub --update-credentials-if-exist
Updating existing credentials
Successfully connected to Docker Hub
```

**Comment by NealArw** [comment]
👉 2.

- Connect docker-hub (or another) credential
- Add in docker-hub invalid docker-hub credentials
- Run `uffizzi connect docker-hub --update-credentials-if-exist`

**Result:** 
```
bash-5.1# bundle exec uffizzi connect docker-hub --update-credentials-if-exist
Updating existing credentials
undefined method `values' for [{:base=>{:account_id=>1, :id=>8, :username=>"uffizzitest1", :password=>"mYYN8P_gJp.H*jRNdz*ZHRU", :project_id=>nil, :created_at=>"2022-07-26T14:26:41.626Z", :updated_at=>"2022-07-26T14:26:41.626Z", :provider_ref=>nil, :state=>"active", :registry_url=>"https://index.docker.io/v1/"}, :attribute=>"username", :raw_type=>"incorrect", :type=>"incorrect", :options=>{}}, {:base=>{:account_id=>1, :id=>8, :username=>"uffizzitest1", :password=>"mYYN8P_gJp.H*jRNdz*ZHRU", :project_id=>nil, :created_at=>"2022-07-26T14:26:41.626Z", :updated_at=>"2022-07-26T14:26:41.626Z", :provider_ref=>nil, :state=>"active", :registry_url=>"https://index.docker.io/v1/"}, :attribute=>"username", :raw_type=>"incorrect", :type=>"incorrect", :options=>{}}]:Array
Did you mean?  values_at
```

**Expected result:**
```
bundle exec uffizzi connect docker-hub --update-credentials-if-exist
Updating existing credentials
We were unable to log you in to docker registry. Please verify that your username and password are correct.
```

👉 3.
Add dot `.` at the end of the sentence  `Updating existing credentials`

**Comment by NealArw** [comment]
👉 **4.**
- Connect docker-hub account 1 (e.g. uffizzitest)
- Deploy private image from this account (deployment-1 should be created)
- Update credentials and connect docker-hub account 2 (e.g. your own account)
- Update deployment-1. Try to update the preview `deployment-1` with the private image from your own account.

**Result:** Deployment failed.
If then start to deploy (not update) private repo from your own account it will be successfully deployed.

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-docker-private.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] test-private-repo
{"id":"deployment-14","url":"https://deployment-14-default.app.qa-gke.uffizzi.com"}

bash-5.1# bundle exec uffizzi connect docker-hub --update-credentials-if-exist
Updating existing credentials.
Successfully connected to Docker Hub.

bash-5.1# bundle exec uffizzi preview update deployment-14 test-compose/uffizzi-compose-webhook-docker-neal.yml
Preview with ID deployment-14 was successfully updated.
[✔] Creating containers...
Done
[✖] Deploying preview...
  [✖] webhook-test-app
Deployment Not Found

bash-5.1# bundle exec uffizzi preview create test-compose/uffizzi-compose-webhook-docker-neal.yml
Preview created with name deployment-15
[✔] Creating containers...
Done
[✔] Deploying preview...
  [✔] webhook-test-app
Done
https://deployment-15-default.app.qa-gke.uffizzi.com
```

Next compose files were used:

`uffizzi-compose-webhook-docker-private.yml`
```
services:
  webhooks-test-app:
    image: uffizzitest/test-private-repo:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
```

`uffizzi-compose-webhook-docker-neal.yml`
```
services:
  webhooks_test_app:
    image: nealarw/webhook-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
