### ISSUE TITLE
Anchors are not parsed via CLI

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#131]
An example compose file:

```
services:
  hello-world:
    image: nginx
    env: &base
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
  redis:
    image: redis
    env: *base

x-uffizzi-ingress:
  service: hello-world
  port: 80
```

Result: `Psych::BadAlias: Unknown alias: base`

**Comment by zipofar** [comment]
### HOW TO TEST: ###
use compose file:
```
x-service: &base-service
    image: nginx

services:
  hello-world: *base-service

x-uffizzi-ingress:
  service: hello-world
  port: 80

```

**Comment by zipofar** [comment]
### Tested according to the check list ###

**Comment by NealArw** [comment]
**TESTED - OK**

```
definitions:
    environment: &env-var
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

services:
  web:
    image: uffizzitest/test_env:latest
    environment: *env-var
        # i.e., value should be added in the Uffizzi Dashboard

x-uffizzi:
  ingress:
    service: web
    port: 80
    
  continuous_preview:
    delete_preview_after: 1h
```

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-env-achor.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] test_env
{"id":"deployment-9","url":"https://deployment-9-default.app.qa-gke.uffizzi.com"}
bash-5.1#
```

```
["POSTGRES_USER"]=> string(8) "postgres"
["POSTGRES_PASSWORD"]=> string(8) "postgres"
```

**Comment by NealArw** [comment]
**TESTED on production - OK**

`CLI + app.uffizzi.com`

```
definitions:
    environment: &env-var
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

services:
  web:
    image: uffizzitest/test_env:latest
    environment: *env-var

x-uffizzi:
  ingress:
    service: web
    port: 80
    
  continuous_preview:
    delete_preview_after: 1h
```

```
# uffizzi preview create -o=json compose.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] test_env
{"id":"deployment-4505","url":"https://deployment-4505-zakary-tillman-1-1e4m0u.app.uffizzi.com"}
#
```

```
["POSTGRES_PASSWORD"]=> string(8) "postgres" 
["POSTGRES_USER"]=> string(8) "postgres"
```
