### ISSUE TITLE
Helath

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_cli#164]
# Describe the bug

Healthchecks are not working

# To Reproduce
```
version: "3.9"

x-uffizzi:
  ingress:
    service: app
    port: 3001

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:1.0.0-beta.6
    ports:
      - 3001:3001
    environment:
      ALL_YES: 1
      NO_INQUIRY: 0
      TRUST_PROXY_HEADER: 1
      DB_URL_DEFAULT: postgres://postgres:p0stgr3s@localhost:5432
  
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr3s"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: "10s"
      timeout: "5s"
      retries: 5
```

# Expected behavior
docker-compose with healthcheck works well
