### ISSUE TITLE
Show error from container registries

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_cli#205]

**Comment by NealArw** [comment]
👉 1. Try to add any compose file via CLI connected to platform.

Result:

```
bash-5.1# beu project compose set -f docker.yml
Server Error:
{:status=>422, :error=>"Unprocessable Entity"}
bash-5.1#
```

```
services:
  webhooks_test_app:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
