### ISSUE TITLE
Add cluster creation to CLI

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_cli#223]

**Comment by gadkins** [comment]
## Create a minimal cluster
```
$ uffizzi cluster create
```  

If no configuration is explicitly passed, create the cluster with the base configuration  

```
kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: testnode
  namespace: test-node
spec:
  ingress:
    class: "nginx"
    host: deleteme2023.uffizzi.cloud
    services:
    - name: test-node-svc
      namespace: test-node
      port: 8080
      ingressAnnotations:
        cert-manager.io/cluster-issuer: "my-uffizzi-letsencrypt"
      certManagerTLSEnabled: true
  ttl: 1h
```
