### ISSUE TITLE
Create cluster from helm chart

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#264]
Add support for creating a cluster given a helm chart.  

```
uffizzi cluster create --chart charts/Chart.yml
```

**Comment by zipofar** [comment]
@gadkins 
I assume we can only handle parameters like this. We can't build chart from `Chart.yaml`
```
    - chart:
        name: cert-manager
        repo: https://charts.jetstack.io
        version: v1.8.0
      # optional field
      values: |-
        installCRDs: true
      release:
        name: cert-manager
        namespace: cert-manager
    # private chart
    - chart:
        name: my-chart
        repo: https://<address/to/private/repo>
        version: <chart version>
        username: <username_for_private_repo>
        password: <password_for_private_repo>
      release:
        name: my-release
        namespace: my-release-namespace
```
