### ISSUE TITLE
BUG: [CLI] No error for command uffizzi preview running with --option

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_cli#85]
1. Create compose file `compose.yml` with a source from GitHub or a file with errors (e.g. change service to s1ervice or set port = 0)
2. Run command `uffizzi preview create -o=json compose.yml`

Result:
1. There are no errors in the console
2. Deployment was not started

File example:

```
s1ervices:
  webhooks-test-app:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
```
